export enum AppointmentStatus {
  NONE = "none",
  SCHEDULED = "scheduled",
}

export type Disease =
  | {
      id: string;
      type: "disease";
      name: string;
      appointmentStatus: AppointmentStatus;
      history: DiseaseHistory[];
    }
  | {
      id: string;
      type: "vaccine";
      name: string;
      appointmentStatus: AppointmentStatus;
      vaccineHistory: VaccineHistory[];
    };

export enum RecordStatus {
  NORMAL = "สีเขียว",
  IMPROVED = "สีเหลือง",
  MONITOR = "สีเเดง",
  RECEIVE = "ได้รับวัคซีนแล้ว",
  OverDUE = "ยังไม่ได้รับวัคซีน",
}

export interface DiseaseHistory {
  visitNo: number;
  examDate: string;
  nextDaysAppointment?: number;
  nextMonthAppointment?: string;
  nextyearAppointment?: number;
  examiner: string;
  doctor: string;
  weight: number;
  height: number;
  pulse: number;
  bloodPressure: string;
  bmi: number;
  status: RecordStatus;
  symptom: string;
  bloodSugar: number;
  treatment: string;
  days: number;
  months: string;
  years: number;
}

export interface VaccineHistory {
  id: string;
  status: RecordStatus;
  vaccineType: string;
  vaccineName: string;

  days: number;
  months: string;
  years: number;

  recommendedAge: string;
  injectionDate: string;
  sideEffects?: string;
  recommendation?: string;
}
export interface Vaccine {
  id: string;
  name: string;
  appointmentStatus: AppointmentStatus;
  vaccineHistory: VaccineHistory[];
}

export enum Gender {
  MALE = "male",
  FEMALE = "female",
}

export interface OfficerPerson {
  fullname: string;
  role: "house" | "nurse";
}

export interface OfficerGroup {
  house: OfficerPerson;
  nurse: OfficerPerson;
}

export interface RelativeAddress {
  house_number: string;
  village_number: string;
  alley: string;
  road: string;
  subdistrict: string;
  district: string;
  province: string;
  zipcode: string;
}

export interface RelativePerson {
  fullname: string;
  phonenumber: string;
  role: "kin" | "caretaker" | "medicine";
  address: RelativeAddress;
}

export interface RelativeGroup {
  kin: RelativePerson;
  caretaker: RelativePerson;
  medicine: RelativePerson;
}

export interface Address {
  house_number: string;
  village: string;
  road: string;
  district: string;
  subDistrict: string;
  province: string;
  postalCode: string;
}

export interface Patient {
  id: number;
  firstName: string;
  lastName: string;
  idCard: string;
  hnId: string;
  gender: Gender;
  age: number;
  month: number;
  day: number;
  right: string;
  nationalId: string;
  nationality: string;
  ethnicity: string;
  weight: number;
  height: number;
  allergy: string;
  phone: string;
  address: Address;
  diseases: Disease[];
  relative: RelativeGroup;
  officer: OfficerGroup;
  location: string;
  year: number;
  purpostAppointment?: string;
  time: string;
}

export const mockPatients: Patient[] = [
  {
    id: 1,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.MALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "09:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        name: "โรคเบาหวาน",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "กุมภาพันธ์",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ตุลาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 2,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "กันยายน",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 10,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน",
          },
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],

    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 2,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 200",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "10:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d3",
        name: "ความดันโลหิตสูง",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert P",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 3,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "11:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        type: "disease",
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 3,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment: "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ",
          },
          {
            visitNo: 2,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
        ],
      },

      {
        id: "d3",
        type: "disease",
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "150/95",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปวดศีรษะ",
            bloodSugar: 110,
            treatment: "ปรับยาความดัน และแนะนำลดเค็ม",
          },
        ],
      },
      {
        id: "v1",
        type: "vaccine",
        name: "วัคซีนเด็ก",
        appointmentStatus: AppointmentStatus.NONE,
        vaccineHistory: [
          {
            id: "vh1",
            status: RecordStatus.RECEIVE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันไวรัสตับอักเสบ",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
          {
            id: "vh2",
            status: RecordStatus.OverDUE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันวัณโรค",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 4,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.MALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "09:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        name: "โรคเบาหวาน",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "กุมภาพันธ์",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ตุลาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 2,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "กันยายน",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 10,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],

    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 5,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 200",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "10:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d3",
        name: "ความดันโลหิตสูง",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert P",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 6,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "11:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        type: "disease",
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 3,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment: "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ",
          },
          {
            visitNo: 2,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
        ],
      },

      {
        id: "d3",
        type: "disease",
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "150/95",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปวดศีรษะ",
            bloodSugar: 110,
            treatment: "ปรับยาความดัน และแนะนำลดเค็ม",
          },
        ],
      },
      {
        id: "v1",
        type: "vaccine",
        name: "วัคซีนเด็ก",
        appointmentStatus: AppointmentStatus.NONE,
        vaccineHistory: [
          {
            id: "vh1",
            status: RecordStatus.RECEIVE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันไวรัสตับอักเสบ",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
          {
            id: "vh2",
            status: RecordStatus.OverDUE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันวัณโรค",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 7,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.MALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "09:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        name: "โรคเบาหวาน",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "กุมภาพันธ์",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ตุลาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 2,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "กันยายน",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 10,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],

    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 8,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 200",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "10:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d3",
        name: "ความดันโลหิตสูง",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert P",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 9,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "11:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        type: "disease",
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 3,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment: "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ",
          },
          {
            visitNo: 2,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
        ],
      },

      {
        id: "d3",
        type: "disease",
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "150/95",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปวดศีรษะ",
            bloodSugar: 110,
            treatment: "ปรับยาความดัน และแนะนำลดเค็ม",
          },
        ],
      },
      {
        id: "v1",
        type: "vaccine",
        name: "วัคซีนเด็ก",
        appointmentStatus: AppointmentStatus.NONE,
        vaccineHistory: [
          {
            id: "vh1",
            status: RecordStatus.RECEIVE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันไวรัสตับอักเสบ",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
          {
            id: "vh2",
            status: RecordStatus.OverDUE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันวัณโรค",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 10,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.MALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "09:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        name: "โรคเบาหวาน",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "กุมภาพันธ์",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ตุลาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 2,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "กันยายน",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 10,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],

    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 11,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 200",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "10:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d3",
        name: "ความดันโลหิตสูง",
        type: "disease",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 2,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment:
              "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ และปฏิบัติตามคำแนะนำแพทย์",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "มีอาการอ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน และติดตามระดับน้ำตาล",
          },
        ],
      },
      {
        id: "d2",
        name: "วัณโรค",
        type: "disease",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "130/85",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ไอเรื้อรัง",
            bloodSugar: 100,
            treatment: "ให้ยาฆ่าเชื้อ 6 เดือน และติดตามอาการทุกเดือน",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert P",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 12,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    purpostAppointment: "ติดตามผลการรักษาโรคเบาหวานและวัณโรค",
    time: "11:00 น.",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        id: "d1",
        type: "disease",
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
        history: [
          {
            visitNo: 3,
            examDate: "2025-10-03",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 54,
            height: 179,
            pulse: 83,
            bloodPressure: "91/53",
            bmi: 22.8,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.IMPROVED,
            symptom: "ปกติ",
            bloodSugar: 126,
            treatment: "HbA1c ลดลง ควบคุมได้ดี รับประทานยาสม่ำเสมอ",
          },
          {
            visitNo: 2,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
          {
            visitNo: 1,
            examDate: "2025-07-01",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นางจิต ใจดี",
            doctor: "นายทองดี ทองสุข",
            weight: 55,
            height: 179,
            pulse: 80,
            bloodPressure: "120/80",
            bmi: 23.1,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.MONITOR,
            symptom: "อ่อนเพลียเล็กน้อย",
            bloodSugar: 145,
            treatment: "แนะนำควบคุมอาหาร ลดของหวาน",
          },
        ],
      },

      {
        id: "d3",
        type: "disease",
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.NONE,
        history: [
          {
            visitNo: 1,
            examDate: "2025-09-15",
            nextDaysAppointment: 5,
            nextMonthAppointment: "ธันวาคม",
            nextyearAppointment: 2569,
            examiner: "นายสมชาย รักษ์ดี",
            doctor: "นพ.กิตติศักดิ์ สุขใจ",
            weight: 60,
            height: 170,
            pulse: 78,
            bloodPressure: "150/95",
            bmi: 24.2,
            days: 2,
            months: "มกราคม",
            years: 2569,
            status: RecordStatus.NORMAL,
            symptom: "ปวดศีรษะ",
            bloodSugar: 110,
            treatment: "ปรับยาความดัน และแนะนำลดเค็ม",
          },
        ],
      },
      {
        id: "v1",
        type: "vaccine",
        name: "วัคซีนเด็ก",
        appointmentStatus: AppointmentStatus.NONE,
        vaccineHistory: [
          {
            id: "vh1",
            status: RecordStatus.RECEIVE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันไวรัสตับอักเสบ",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
          {
            id: "vh2",
            status: RecordStatus.OverDUE,
            vaccineType: "HBC1",
            vaccineName: "วัคซีนป้องกันวัณโรค",
            days: 2,
            months: "มกราคม",
            years: 2569,
            recommendedAge: "เเรกเกิด",
            injectionDate: "2025-06-01",
            sideEffects: "ปวดแขนเล็กน้อย",
            recommendation: "ควรฉีดซ้ำทุกปี",
          },
        ],
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
];
