export enum AppointmentStatus {
  NONE = "none",
  SCHEDULED = "scheduled",
}

export interface Disease {
  name: string;
  appointmentStatus: AppointmentStatus;
}

export enum Gender {
  MALE = "male",
  FEMALE = "female",
}

export interface OfficerPerson {
  fullname: string;
  role: "house" | "nurse";
}

export interface OfficerGroup {
  house: OfficerPerson;
  nurse: OfficerPerson;
}

export interface RelativeAddress {
  house_number: string;
  village_number: string;
  alley: string;
  road: string;
  subdistrict: string;
  district: string;
  province: string;
  zipcode: string;
}

export interface RelativePerson {
  fullname: string;
  phonenumber: string;
  role: "kin" | "caretaker" | "medicine";
  address: RelativeAddress;
}

export interface RelativeGroup {
  kin: RelativePerson;
  caretaker: RelativePerson;
  medicine: RelativePerson;
}

export interface Address {
  house_number: string;
  village: string;
  road: string;
  district: string;
  subDistrict: string;
  province: string;
  postalCode: string;
}

export interface Patient {
  id: number;
  firstName: string;
  lastName: string;
  idCard: string;
  hnId: string;
  gender: Gender;
  age: number;
  month: number;
  day: number;
  right: string;
  nationalId: string;
  nationality: string;
  ethnicity: string;
  weight: number;
  height: number;
  allergy: string;
  phone: string;
  address: Address;
  diseases: Disease[];
  relative: RelativeGroup;
  officer: OfficerGroup;
  location: string;
  year: number;
}

export const mockPatients: Patient[] = [
  {
    id: 1,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.MALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.NONE,
      },
      {
        name: "วัณโรค",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 2,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2569,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 200",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert P",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 3,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 4,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 5,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 6,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 7,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 8,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 9,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 10,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 11,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 12,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.NONE,
      },
      {
        name: "วัณโรค",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 13,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 14,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 15,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 16,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 17,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 18,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 19,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 20,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 21,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 22,
    firstName: "สมชาย",
    lastName: "ใจดี",
    idCard: "1-2345-67890-12-3",
    hnId: "HN000123",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.NONE,
      },
      {
        name: "วัณโรค",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 23,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 24,
    firstName: "อนันต์",
    lastName: "วัฒนา",
    idCard: "1-1111-22222-33-4",
    hnId: "HN000125",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "โรคความดันโลหิตสูง",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
      {
        name: "โรคเบาหวาน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 25,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 26,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 27,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 28,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 29,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 30,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2004,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
  {
    id: 31,
    firstName: "สุดารัตน์",
    lastName: "สุขใจ",
    idCard: "1-9876-54321-09-8",
    hnId: "HN000124",
    gender: Gender.FEMALE,
    age: 20,
    month: 3,
    day: 2,
    year: 2024,
    nationalId: "2-1023-01357-90-4",
    right: "บัตรทอง",
    nationality: "ไทย",
    ethnicity: "ไทย",
    weight: 50,
    height: 179,
    allergy: "ไม่มี",
    phone: "123-4567890",
    location: "อาคาร A ชั้น 2 ห้อง 201",
    address: {
      house_number: "123/45",
      village: "ไม่มี",
      road: "ไม่มี",
      district: "หนองนา",
      subDistrict: "หนองนา",
      province: "นครปฐม",
      postalCode: "77770",
    },
    diseases: [
      {
        name: "วัคซีน",
        appointmentStatus: AppointmentStatus.SCHEDULED,
      },
    ],
    relative: {
      kin: {
        fullname: "Mr.Prasert Wongprasert",
        phonenumber: "0811112233",
        role: "kin",
        address: {
          house_number: "45/8",
          village_number: "6",
          alley: "Soi Rama 2 Soi 33",
          road: "Rama 2 Road",
          subdistrict: "Bang Mot",
          district: "Chom Thong",
          province: "Bangkok",
          zipcode: "10150",
        },
      },

      caretaker: {
        fullname: "Miss Patcharin Siriwan",
        phonenumber: "0872223344",
        role: "caretaker",
        address: {
          house_number: "120/4",
          village_number: "9",
          alley: "Soi Ladprao 101",
          road: "Ladprao Road",
          subdistrict: "Wang Thonglang",
          district: "Wang Thonglang",
          province: "Bangkok",
          zipcode: "10310",
        },
      },

      medicine: {
        fullname: "Mr.Nopparat Jaisom",
        phonenumber: "0851237789",
        role: "medicine",
        address: {
          house_number: "77/5",
          village_number: "4",
          alley: "Soi Phahonyothin 34",
          road: "Phahonyothin Road",
          subdistrict: "Lat Yao",
          district: "Chatuchak",
          province: "Bangkok",
          zipcode: "10900",
        },
      },
    },
    officer: {
      house: {
        fullname: "Ms.Kanyarat Sae-Tang",
        role: "house",
      },
      nurse: {
        fullname: "Miss Nanticha Phonchai",
        role: "nurse",
      },
    },
  },
];
