import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "../globals.css";
import { NavBar } from "@/components/nav-bar";
import { LayoutWrapper } from "@/components/layour-wrapper";

const ibmPlexThai = IBM_Plex_Sans_Thai({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-thai",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Phoss care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className={`${ibmPlexThai.variable} font-sans antialiased`}>
        <NavBar />
        <LayoutWrapper>
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
