import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarInset } from "@/shadcn/ui/sidebar";
import { NavBar } from "@/components/nav-bar";

const ibmPlexThai = IBM_Plex_Sans_Thai({
  subsets: ["thai", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Phoss care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexThai.variable} antialiased`}
      >
        <SidebarProvider>
          <SidebarInset className="min-h-screen">
            <AppSidebar />
            <NavBar />
            {children}
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
